# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electr\xf3nico')),
                ('display_name', models.CharField(blank=True, max_length=50, verbose_name='nombre')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('role', models.PositiveIntegerField(choices=[(0, 'Inactivo'), (1, 'Consultor'), (2, 'Operador'), (3, 'Administrador')], default=0, verbose_name='rol')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
    ]
