# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 15:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='marca de tiempo')),
                ('message', models.CharField(max_length=1024, verbose_name='mensaje')),
                ('details', models.TextField(blank=True, verbose_name='detalles')),
                ('ref_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces', to=settings.AUTH_USER_MODEL, verbose_name='usuario de referencia')),
            ],
            options={
                'ordering': ('-timestamp',),
                'verbose_name': 'traza',
                'verbose_name_plural': 'trazas',
            },
        ),
    ]
