# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 15:50
from __future__ import unicode_literals

import common.snippets.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='nombre')),
                ('slug', common.snippets.fields.AutoSlugField(allow_duplicates=False, blank=True, editable=False, max_length=512, overwrite=True, populate_from=('name',), separator='-', verbose_name='slug')),
            ],
            options={
                'verbose_name': 'facultad',
                'verbose_name_plural': 'facultades',
            },
        ),
        migrations.CreateModel(
            name='PaymentRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='nombre')),
                ('slug', common.snippets.fields.AutoSlugField(allow_duplicates=False, blank=True, editable=False, max_length=512, overwrite=True, populate_from=('name',), separator='-', verbose_name='slug')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto a pagar')),
                ('description', models.TextField(blank=True, verbose_name='descripci\xf3n')),
            ],
            options={
                'ordering': ('payment_type', 'amount'),
                'verbose_name': 'regla de pago',
                'verbose_name_plural': 'reglas de pago',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='nombre')),
                ('slug', common.snippets.fields.AutoSlugField(allow_duplicates=False, blank=True, editable=False, max_length=512, overwrite=True, populate_from=('name',), separator='-', verbose_name='slug')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ordernamiento')),
                ('alias', models.CharField(blank=True, max_length=5, verbose_name='alias')),
                ('regularity', models.PositiveIntegerField(choices=[(0, 'Ocasional'), (1, 'Frecuente')], default=1, verbose_name='regularidad')),
                ('allow_rules', models.BooleanField(default=False, verbose_name='permite reglas de pago')),
            ],
            options={
                'ordering': ('ordering', 'slug'),
                'verbose_name': 'tipo de pago',
                'verbose_name_plural': 'tipos de pago',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='nombre')),
                ('slug', common.snippets.fields.AutoSlugField(allow_duplicates=False, blank=True, editable=False, max_length=512, overwrite=True, populate_from=('name',), separator='-', verbose_name='slug')),
                ('logo', models.ImageField(blank=True, upload_to='logos', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'universidad',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='nombre')),
                ('slug', common.snippets.fields.AutoSlugField(allow_duplicates=False, blank=True, editable=False, max_length=512, overwrite=True, populate_from=('name',), separator='-', verbose_name='slug')),
                ('structure', models.CharField(choices=[('0:5', 'Cinco a\xf1os con preparatoria'), ('1:4', 'Cuatro a\xf1os'), ('1:5', 'Cinco a\xf1os'), ('1:6', 'Seis a\xf1os')], default='1:5', max_length=3, verbose_name='estructura de a\xf1os')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='core.Faculty', verbose_name='facultad')),
            ],
            options={
                'verbose_name': 'especialidad',
                'verbose_name_plural': 'especialidades',
            },
        ),
        migrations.CreateModel(
            name='StudentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='nombre')),
                ('slug', common.snippets.fields.AutoSlugField(allow_duplicates=False, blank=True, editable=False, max_length=512, overwrite=True, populate_from=('name',), separator='-', verbose_name='slug')),
            ],
            options={
                'verbose_name': 'tipo de estudiante',
                'verbose_name_plural': 'tipos de estudiante',
            },
        ),
        migrations.AddField(
            model_name='paymentrule',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.PaymentType', verbose_name='tipo de pago'),
        ),
    ]
