# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 15:50
from __future__ import unicode_literals

import common.snippets.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='nombre')),
                ('slug', common.snippets.fields.AutoSlugField(allow_duplicates=False, blank=True, editable=False, max_length=512, overwrite=True, populate_from=('name',), separator='-', verbose_name='slug')),
                ('status', models.PositiveIntegerField(choices=[(0, 'No calculado'), (1, 'Calculando pagos'), (2, 'Listo'), (3, 'Cerrado')], default=0, verbose_name='estado')),
                ('description', models.TextField(blank=True, verbose_name='descripci\xf3n')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de apertura')),
                ('date_generated', models.DateTimeField(blank=True, null=True, verbose_name='fecha de c\xe1lculo')),
                ('date_closed', models.DateTimeField(blank=True, null=True, verbose_name='fecha de cierre')),
                ('generated_by', models.CharField(blank=True, max_length=512, verbose_name='calculado por')),
            ],
            options={
                'ordering': ('-date_closed', 'date_created'),
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto a pagar')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.PaymentType', verbose_name='tipo de pago')),
            ],
            options={
                'verbose_name': 'registro de pago',
                'verbose_name_plural': 'registros de pago',
            },
        ),
        migrations.CreateModel(
            name='PaymentRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refunded', models.BooleanField(default=False, verbose_name='reintegrada')),
                ('year', models.IntegerField(choices=[(0, 'Preparatoria'), (1, '1ro'), (2, '2do'), (3, '3ro'), (4, '4to'), (5, '5to'), (6, '6to')], default=1, verbose_name='a\xf1o que cursa')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='payments.Payment', verbose_name='pago')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.Specialty', verbose_name='especialidad')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='students.Student', verbose_name='estudiante')),
            ],
            options={
                'verbose_name': 'fila de pago',
                'verbose_name_plural': 'filas de pago',
            },
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='payments.PaymentRow', verbose_name='fila'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentrow',
            unique_together=set([('payment', 'student')]),
        ),
        migrations.AlterUniqueTogether(
            name='paymentrecord',
            unique_together=set([('row', 'payment_type')]),
        ),
    ]
